
import { GoogleGenAI } from "@google/genai";

const SYSTEM_PROMPT = `
Transform the subject(s) from the uploaded image(s) into a full-body realistic 3D character model suitable for the Grand Theft Auto V gameplay environment (RAGE engine style). 
MUST include legs and feet, even if not present in reference.
AESTHETIC: Focus on realistic, slightly gritty textures for skin, cloth, denim, and leather. High-quality character snapshot taken directly from the game engine.
LIGHTING: Strong, natural highlights and defined shadows (outdoor game lighting).
AVOID: LEGO or plastic aesthetics, 2D loading screen illustration style, cartoon proportions, hyper-realistic photography, smooth textureless surfaces, cropped images.
RETAIN: Identity, facial features, skin tone, hair style, and specific clothing patterns converted to high-detail game textures.
PROPORTIONS: Realistic adult human proportions typical of GTA V.
`;

export async function transformToGTA(base64Image: string, userPrompt: string): Promise<string> {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  
  // Extract data type from base64 if present
  const match = base64Image.match(/^data:(image\/\w+);base64,(.+)$/);
  const mimeType = match ? match[1] : 'image/png';
  const data = match ? match[2] : base64Image;

  const prompt = userPrompt.trim() 
    ? `${SYSTEM_PROMPT}\nAdditional User Instructions: ${userPrompt}`
    : SYSTEM_PROMPT;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: data,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
    });

    let resultImageUrl = '';
    
    // Iterate through parts to find the image part
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          resultImageUrl = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }
    }

    if (!resultImageUrl) {
      throw new Error("No image was generated by the model. Check the input and try again.");
    }

    return resultImageUrl;
  } catch (error: any) {
    console.error("Gemini Transformation Error:", error);
    throw new Error(error.message || "Failed to transform image. Please try again.");
  }
}
